spring.application.name=api-gateway
server.port=8089
# ksef producer
spring.cloud.gateway.routes[0].id=producer-service
spring.cloud.gateway.routes[0[.uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/dokument/**

# minio metadata service
spring.cloud.gateway.routes[1].id=metadata-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/metadata/**

# minio storage service
spring.cloud.gateway.routes[2].id=storage-service
spring.cloud.gateway.routes[2].uri=http://localhost:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/storage/**
